### ISSUE TITLE
Helm chart values file contains uncommented lines which are part of an example

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/bpn-did-resolution-service#78]
## Describe the bug

File charts/bdrs-server/values.yaml in lines 217-227 contains the following sequence:

```
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1.5
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi
```
The uncommented `limits` and `requests` section is not valid, they are actually part of the comment above.

Same applies to file charts/bdrs-server-memory/values.yaml

### To Reproduce

n/a

### Expected behavior

`limits` and `requests` section is commented out

### Screenshots/Error Messages

n/a

## Context Information

n/a

## Possible Implementation

Comment the appropriate lines
